opencurrents/opencurrents

openCurrents/templates/community.html
=> community update - fix back

openCurrents/templates/live-dashboard.html
Needs to be hooked in before being merged
=> #97: add invite-volunteer checkbox

openCurrents/templates/confirm-account.html
monthly_updates is called from form data when user_account is saved in process_email_confirmation
=> naming checkbox input monthly_updates

openCurrents/forms.py, openCurrents/models.py, openCurrents/templates/time-tracker.html, openCurrents/urls.py, openCurrents/views.py
Added the manual tracking of hours for volunteers
=> Manual tracking

openCurrents/forms.py, openCurrents/models.py, openCurrents/templates/time-tracker.html, openCurrents/urls.py, openCurrents/views.py
=> Manual tracking revisited

openCurrents/templates/check-email.html, openCurrents/templates/live-dashboard.html, openCurrents/templates/profile.html, openCurrents/urls.py, openCurrents/views.py
- live-dashboard now prepends new volunteer sign ins to the top of the list.
- profile page will now display welcome popup only on the first visit through use of browser localStorage.
- process_resend now redirects with a status_msg included. status_msg displays after Resend is hit.
_DONE: status success/fail flag passed to template instead of entire status_msg_
- sendContactEmail added to alert coordinators of new user registrations to their event. Optional contact message will be included in email if provided.
_DONE: contact email sends with subject line_
- DatetimeEncoder allows for serialization of datetime from sendContactEmail to mandrill template.
=> Multiple small changes, please see comments

openCurrents/templates/event-detail.html
Timezone inconsistency in profile page and event-detail page fixed
=> Timezone event detail

openCurrents/templates/live-dashboard.html
in add-volunteer live-dashboard function
=> adding email-error messsage and reg-ex test for valid email 

openCurrents/templates/approve-hours.html, openCurrents/templates/profile.html, openCurrents/views.py
1. redirection to admin-profile when all the manual trackings have been approved.
2. 
a. Display of approve hour pop-up in profile page if its the first login of the week.
b. Display of approve hours button instead of create event of there are any un-approved hour trackings.
Files changed:
1. Views.py
2. admin-profile.html
3. profile.html
=> Approve hours Bug-fixes

openCurrents/forms.py, openCurrents/templates/create-event.html
Validate form data and display error at top of page.
=> Create-event time and date form validation

openCurrents/static/css/app.css, openCurrents/templates/admin-profile.html, openCurrents/templates/create-event.html, openCurrents/templates/edit-event.html, openCurrents/templates/profile.html
Revised styling of admin-profile, including dropdown menus for each event. Also added plus icons to create and edit event pages.
=> Admin-profile menus

openCurrents/templates/admin-profile.html, openCurrents/views.py
Fixing admin-profile display of MN events
=> display GR events only

openCurrents/views.py
1. Pop up for admin when there is hours to be approved and first time login for the week issue fixed.
Files changed:
a) views.py
=> Approve hours issue 281

openCurrents/static/css/app.css, openCurrents/templates/login.html, openCurrents/views.py
Implemented using sessions.
Files changed:
1. views.py
=> Login remember me

openCurrents/templates/approve-hours.html, openCurrents/views.py
Files changed:
1. views.py
2. approve-hours.html
=> Approve hours issue 315

openCurrents/views.py
=> Time tracker issue 327

openCurrents/templates/invite-volunteers.html
Including num_vols=0 in skip. Needed for msg on admin-profile
=> Fix Skip on invite-volunteers

openCurrents/static/css/app.css, openCurrents/templates/admin-profile.html, openCurrents/templates/live-dashboard.html, openCurrents/views.py
Files changed:
1. views.py
2. live-dashboard.html
=> Event checkin issue 303.

openCurrents/forms.py
@karbmk FYI, here is why this change is important:
https://snakeycode.wordpress.com/2014/11/20/django-forms-choices-and-caching/
=> dynamic choices list

openCurrents/forms.py, openCurrents/templates/confirm-account.html
Data from HTML wasn't passed to the forms as expected which has been rectified.
=> signup_confirm-account: issue #11 fixed

openCurrents/views.py
@nickolashe please let me know when this is merged and I will update the email templates
=> add event name to volunteer-messaged and coordinator-messaged emails

openCurrents/views.py
Reverts opencurrents/opencurrents#603
=> Revert "add event name to volunteer-messaged and coordinator-messaged emails"

openCurrents/static/js/end_scripts.js
=> Add google analytics

openCurrents/forms.py, openCurrents/static/css/app.css, openCurrents/static/css/custom-radio.css, openCurrents/templates/create-event.html
This fixes radio buttons, but still needs to address error received by Shavone from Bike Austin when clicking submit on create-event. Not sure of error message and I did not receive the error when I tried it.
=> Create event fix (WIP)

openCurrents/templates/layouts/base.html, openCurrents/views.py
=> marketplace: status_msg and fixes

openCurrents/forms.py
=> start time too far in past

openCurrents/static/css/app.css, openCurrents/templates/event-detail.html, openCurrents/views.py
@nickolashe not sure why circleci test failed?
=> Event detail names

openCurrents/forms.py, openCurrents/templates/marketplace.html
=> biz details

openCurrents/interfaces/bizadmin.py, openCurrents/interfaces/community.py, openCurrents/interfaces/ocuser.py, openCurrents/interfaces/orgs.py, openCurrents/tests/test_public_record.py, openCurrents/views.py
=> include pending currents 

openCurrents/interfaces/bizadmin.py, openCurrents/interfaces/community.py, openCurrents/interfaces/orgs.py, openCurrents/templates/hours-detail.html, openCurrents/templates/org-admin.html, openCurrents/templates/profile.html, openCurrents/templatetags/tags.py, openCurrents/tests/interfaces/common.py, openCurrents/tests/test_npf_admin_profile.py, openCurrents/tests/test_personal_message.py, openCurrents/tests/test_user_profile.py, openCurrents/views.py
@nickolashe please review float numbers formatting implementation per our yesterday's discussion, thanks!
Email parser is implemented now.
=> Kostya profile additions
